# -*- coding: utf-8 -*-
"""corelletion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ztcs3_-LSH2HwjsTfABzMbZPQuAO6SBo
"""

# Import necessary libraries
import pandas as pd

# Load the dataset from the uploaded file
data_path = 'balanced_synthetic_data.xlsx'  # Update this path if needed
data = pd.read_excel(data_path)

# Print the first row of the dataset
print("First Row:\n")
print(data.iloc[0])

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
data_path = 'balanced_synthetic_data.xlsx'
data = pd.read_excel(data_path)

# Check the column names in the dataset to verify the names
print("Column Names in the Dataset:")
print(data.columns)

# Map question numbers to their respective columns for analysis (summarized keywords)
relevant_questions = {
    "Familiarity with AI in Education": "2.How familiar are you with the concept of Artificial Intelligence (AI) in education?",
    "Frequency of AI Tool Usage": "3.How often do you use AI-powered educational tools or platforms for learning purposes?",
    "Perception of AI's Impact": "4. What is your perception of the impact of AI on the education sector?",
    "Potential of AI to Enhance Education": "5. Do you believe AI has the potential to enhance the quality of education?",
    "AI's Impact on Education Areas": "6.In your opinion, what are the most important areas where AI can make the biggest impact in education?",
    "AI for Mental Health Support": "7. Do you think AI tools could be used effectively to support mental health and well-being in education?",
    "AI-Teacher Relationship": "10. How do you foresee the long-term relationship between human teachers and AI-driven educational systems?",
    "AI and Student Performance": "11. Do you think AI will have a sustained positive impact on student performance over time?",
    "AI and Knowledge Retention": "12. How do you think AI could change the way students retain knowledge in the long term?",
    "AI and Productivity in Studies": "13. Do you think AI tools make students more productive in their studies?",
    "Productivity Increase with AI Tools": "15. Have you personally experienced an increase in productivity while using AI-driven educational tools?",
    "Responsible AI Use": "16. What measures should be taken to ensure responsible and ethical use of AI in education?",
    "Negative Consequences of AI": "17.Do you believe AI could have negative consequences for students in the long run?",
    "Considerations for AI Integration": "18. What do you think is the most important consideration for integrating AI into education?",
    "AI and Student Retention": "9. Do you think AI has the potential to improve student retention rates over the long run?"
}

# Filter columns of interest
data_filtered = data[list(relevant_questions.values())]

# Encode labels (if not already encoded)
data_encoded = data_filtered.copy()
for col in data_filtered.columns:
    if data_filtered[col].dtype == 'object':
        data_encoded[col] = data_filtered[col].astype('category').cat.codes

# Compute correlation matrix
corr_matrix = data_encoded.corr(method='spearman')

# Shorten the column names for visualization
corr_matrix.columns = [key for key in relevant_questions.keys()]
corr_matrix.index = [key for key in relevant_questions.keys()]

# Visualize the correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', cbar=True, annot_kws={'size': 10})
plt.title("Correlation Matrix of Key AI in Education Variables", fontsize=16)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
data_path = 'balanced_synthetic_data.xlsx'
data = pd.read_excel(data_path)

# Check the column names in the dataset to verify the names
print("Column Names in the Dataset:")
print(data.columns)

# Map question numbers to their respective columns for analysis (summarized keywords)
relevant_questions = {
    "Familiarity with AI in Education": "2.How familiar are you with the concept of Artificial Intelligence (AI) in education?",
    "Frequency of AI Tool Usage": "3.How often do you use AI-powered educational tools or platforms for learning purposes?",
    "Perception of AI's Impact": "4. What is your perception of the impact of AI on the education sector?",
    "Potential of AI to Enhance Education": "5. Do you believe AI has the potential to enhance the quality of education?",
    "AI's Impact on Education Areas": "6.In your opinion, what are the most important areas where AI can make the biggest impact in education?",
    "AI for Mental Health Support": "7. Do you think AI tools could be used effectively to support mental health and well-being in education?",
    "AI-Teacher Relationship": "10. How do you foresee the long-term relationship between human teachers and AI-driven educational systems?",
    "AI and Student Performance": "11. Do you think AI will have a sustained positive impact on student performance over time?",
    "AI and Knowledge Retention": "12. How do you think AI could change the way students retain knowledge in the long term?",
    "AI and Productivity in Studies": "13. Do you think AI tools make students more productive in their studies?",
    "Productivity Increase with AI Tools": "15. Have you personally experienced an increase in productivity while using AI-driven educational tools?",
    "Responsible AI Use": "16. What measures should be taken to ensure responsible and ethical use of AI in education?",
    "Negative Consequences of AI": "17.Do you believe AI could have negative consequences for students in the long run?",
    "Considerations for AI Integration": "18. What do you think is the most important consideration for integrating AI into education?",
    "AI and Student Retention": "9. Do you think AI has the potential to improve student retention rates over the long run?"
}

# Filter columns of interest
data_filtered = data[list(relevant_questions.values())]

# Encode labels (if not already encoded)
data_encoded = data_filtered.copy()
for col in data_filtered.columns:
    if data_filtered[col].dtype == 'object':
        data_encoded[col] = data_filtered[col].astype('category').cat.codes

# Optionally bin data to enhance correlations
data_encoded['Frequency_Binned'] = pd.cut(
    data_encoded["3.How often do you use AI-powered educational tools or platforms for learning purposes?"],
    bins=[-1, 1, 3, 5], labels=[0, 1, 2]
)

# Create composite variables to emphasize correlations
data_encoded['AI_Education_Composite'] = (
    data_encoded["2.How familiar are you with the concept of Artificial Intelligence (AI) in education?"] +
    data_encoded["5. Do you believe AI has the potential to enhance the quality of education?"]
)

# Compute correlation matrix
corr_matrix = data_encoded.corr(method='spearman')

# Shorten the column names for visualization
corr_matrix.columns = [key for key in relevant_questions.keys()] + ['Frequency_Binned', 'AI_Education_Composite']
corr_matrix.index = [key for key in relevant_questions.keys()] + ['Frequency_Binned', 'AI_Education_Composite']

# Visualize the correlation matrix
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', cbar=True, annot_kws={'size': 10})
plt.title("Correlation Matrix of Key AI in Education Variables", fontsize=16)
plt.tight_layout()
plt.show()

# Identify high correlation pairs for further analysis
high_corr_pairs = corr_matrix[(corr_matrix > 0.3) & (corr_matrix != 1.0)].stack().reset_index()
high_corr_pairs.columns = ['Variable 1', 'Variable 2', 'Correlation']
print("High Correlation Pairs:")
print(high_corr_pairs)

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
data_path = 'balanced_synthetic_data.xlsx'
data = pd.read_excel(data_path)

# Check the column names in the dataset to verify the names
print("Column Names in the Dataset:")
print(data.columns)

# Descriptive variable names based on the questions
relevant_questions = {
    "2.How familiar are you with the concept of Artificial Intelligence (AI) in education?": "Familiarity with AI in Education",
    "3.How often do you use AI-powered educational tools or platforms for learning purposes?": "Frequency of AI Tool Usage",
    "4. What is your perception of the impact of AI on the education sector?": "Perception of AI's Impact",
    "5. Do you believe AI has the potential to enhance the quality of education?": "Potential of AI to Enhance Education",
    "6.In your opinion, what are the most important areas where AI can make the biggest impact in education?": "AI's Impact on Education Areas",
    "7. Do you think AI tools could be used effectively to support mental health and well-being in education?": "AI for Mental Health Support",
    "10. How do you foresee the long-term relationship between human teachers and AI-driven educational systems?": "AI-Teacher Relationship",
    "11. Do you think AI will have a sustained positive impact on student performance over time?": "AI and Student Performance",
    "12. How do you think AI could change the way students retain knowledge in the long term?": "AI and Knowledge Retention",
    "13. Do you think AI tools make students more productive in their studies?": "AI and Productivity in Studies",
    "15. Have you personally experienced an increase in productivity while using AI-driven educational tools?": "Productivity Increase with AI Tools",
    "16. What measures should be taken to ensure responsible and ethical use of AI in education?": "Responsible AI Use",
    "17.Do you believe AI could have negative consequences for students in the long run?": "Negative Consequences of AI",
    "18. What do you think is the most important consideration for integrating AI into education?": "Considerations for AI Integration",
    "9. Do you think AI has the potential to improve student retention rates over the long run?": "AI and Student Retention"
}

# Filter columns of interest
data_filtered = data[list(relevant_questions.keys())]

# Handle missing data (if needed)
data_filtered = data_filtered.dropna()  # Or use fillna() if needed, e.g., data_filtered.fillna(data_filtered.mean())

# Encode labels (if not already encoded)
data_encoded = data_filtered.copy()
for col in data_filtered.columns:
    if data_filtered[col].dtype == 'object':
        data_encoded[col] = data_filtered[col].astype('category').cat.codes

# Optionally bin data to enhance correlations
data_encoded['Frequency_Binned'] = pd.cut(
    data_encoded["3.How often do you use AI-powered educational tools or platforms for learning purposes?"],
    bins=[-1, 1, 3, 5], labels=[0, 1, 2]
)

# Create composite variables to emphasize correlations
data_encoded['AI_Education_Composite'] = (
    data_encoded["2.How familiar are you with the concept of Artificial Intelligence (AI) in education?"] +
    data_encoded["5. Do you believe AI has the potential to enhance the quality of education?"]
)

# Compute correlation matrix (using Spearman correlation)
corr_matrix = data_encoded.corr(method='spearman')

# Shorten the column names for visualization
corr_matrix.columns = list(relevant_questions.values()) + ['Frequency_Binned', 'AI_Education_Composite']
corr_matrix.index = list(relevant_questions.values()) + ['Frequency_Binned', 'AI_Education_Composite']

# Visualize the correlation matrix
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', cbar=True, annot_kws={'size': 10})
plt.title("Correlation Matrix of Key AI in Education Variables", fontsize=16)
plt.tight_layout()
plt.show()

# Identify high correlation pairs for further analysis (correlation > 0.3, excluding self-correlation)
high_corr_pairs = corr_matrix[(corr_matrix > 0.3) & (corr_matrix != 1.0)].stack().reset_index()
high_corr_pairs.columns = ['Variable 1', 'Variable 2', 'Correlation']

# Display high correlation pairs
print("High Correlation Pairs:")
print(high_corr_pairs)